### ISSUE TITLE
Settings Revamp

### ISSUE THREAD

**Issue by dvoraen** [dvoraen/arxcode#2]
# Overview
Rework the `@settings` command so that the character and account settings are stored in the database as (categorized) models.

### Database
- [x] Create a Django app for settings.
- [x] Create the models for the data.
- [x] Configure the admin portal for the new models.
- [ ] Create initial migrations.
- [ ] Write data migration as a separate migration.
  - [ ] Create objects for existing characters.
  - [ ] Set data from existing settings.
  - [ ] Delete attributes and tags that functioned as settings.
  - [ ] Write reversal method in case something goes wrong.

### Implementation
- [x] Remove old settings command from use.
- [x] Write helper methods for models.
- [ ] Write `utils` methods for acquiring settings from database.
- [x] Implement `CmdSettings` functionality.
- [ ] Update character creation to create settings models for the new character.

#### `account` settings
- [ ] apply_output_newline
- [ ] allow_bb_altread
  - [ ] update web template
- [ ] strip_ansi_names
- [ ] strip_ascii_text
#### `general` settings
- [ ] brief_mode
- [ ] private_mode
- [ ] verbose_where_mode
- [ ] ic_only_mode
- [ ] show_model_emits
- [ ] show_weather_emits
#### `rp` settings
- [ ] apply_emit_label
- [ ] apply_pose_break
- [ ] pose_quote_color
- [ ] pose_mention_color
- [ ] place_name_color
#### `comm` settings
- [ ] highlight_chan_mention
- [ ] show_msg_text
- [ ] show_msg_notice
- [ ] show_msg_delivery
